language: php
php:
  - 5.5
  - 5.6
before_install:
  - printf "\n" | pecl install yaml
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install: composer install
script: phpunit tests/
